version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    expose:
      - "5432"
    command: npm run start
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    env_file:
      - .env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
