FROM node:19-bullseye As development

WORKDIR /usr/src/app

COPY prisma ./prisma/

COPY .env .env

COPY . .

RUN npm i

RUN npm run build

RUN npx prisma generate

CMD ["npm", "run", "start"]


FROM node:19-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm i glob rimraf

COPY . .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]
